name: pari_technical_test
description: "Technical Test for Pari - Ahmad Tuflihun"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pretty_http_logger: ^1.0.4
  get_it: ^8.0.0
  hive: ^2.0.4
  go_router: ^14.7.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
