name: pari_technical_test
description: "Technical Test for PARI - Ahmad Tuflihun"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pretty_http_logger: ^1.0.4
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.8.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
